config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'posts#index'

  resources :posts do
    resources :comments
  end

  resources :users, :only => [:show]

  match 'like', to: 'likes#like', via: :post

  match 'unlike', to: 'likes#unlike', via: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: :post_id}




end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :image, presence: true
  validates :user_id, presence: true
  has_attached_file :image, :style => {:medium => "300x300!", :large => "500x500#"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :comments, dependent: :destroy
  has_many :likes , dependent: :destroy
  has_many :liking_users, :through => :likes, :source => :user, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, style: {medium: "300x300", thumb: "100x100"}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post, dependent: :destroy


  def like!(post)

    self.likes.create!(post_id: post.id)

  end

  def unlike!(post)

    like = self.likes.find_by_post_id(post.id)
    like.destroy!

  end

  def liked?(post)

    self.likes.find_by_post_id(post.id)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper Webpacker::Helper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :define_post
  skip_before_action :verify_authenticity_token
  respond_to :json

  def show
    @comments = @post.comments
  end

  def index
    @comments = @post.comments
  end

  def new

  end

  def create

    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
       format.html {head :ok}
       format.json {render json: @comment.to_json}
       format.js {head :ok}
      end
    else
       flash[:alert] = "Comment could not be saved"
       redirect_to root_path
    end

  end

  def edit

  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json {render json: @comment.to_json}
        format.js
      end
    else
      flash[:alert] = "Comment could not be deleted"
      format.json { render json: @comment.errors }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def define_post

    @post = Post.find(params[:post_id])

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
respond_to :js

def like

  @user = current_user
  @post = Post.find(params[:post_id])
  @user.like!(@post)

end

def unlike

  @user = current_user
  @like = @user.likes.find_by_post_id(params[:post_id])
  @post = Post.find(params[:post_id])
  @like.destroy!

end

private

  def

  def define_post


  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :users_post, only: [:update, :edit, :destroy]
skip_before_action :verify_authenticity_token

def index
  @posts = Post.all
end

def new
  @post = current_user.posts.build
end


def create
  @post = current_user.posts.build(post_params)
  if @post.save
     respond_to do |format|
       format.html {redirect_to posts_path}
       format.js
     end
   else
     flash[:alert] = "Your new post couldn't be created!  Please check the form."
     render :new
   end
end

def show
  @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])
  @post.update(post_params)
  redirect_to(post_path(@post))
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

private




  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def users_post
    @post = Post.find(params[:id])
    unless current_user == @post.user
      flash[:error] = "Cannot access this page!"
      redirect_to root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params

    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :avatar)

  end

  def account_update_params

    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password, :avatar)

  end

end

app/controllers/s_controller.rb
class SController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = User.find(params[:id])
  @posts = @user.posts
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/s_helper.rb
module SHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
    <%= javascript_pack_tag 'application' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <a class="navbar-brand" href="/"><%= fa_icon "camera-retro"  %> | ICON</a>
  <!-- <div class="search">
    <ul class="nav navbar-nav nav-search">
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= fa_icon "search" %></span>
        <li class="nav-item active">
          <input type="text" class="form-control" placeholder="Search.." aria-describedby="basic-addon1">
        </li>
      </div>
    </ul>
  </div> -->
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link nav-icon" href="#"><%= fa_icon "compass"  %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-icon" href="#"><%= fa_icon "heart"  %></a>
      </li>

      <li class="dropdown">
        <a class="dropdown-toggle"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%=image_tag current_user.avatar, size: "50x50"%><span class="current-user-nav"></span>
        </a>
          <ul class="dropdown-menu">
                <li><a role="dropdown-item" href="#"><%= link_to('Edit registration', edit_user_registration_path) %></a></li>
                <li><a role="dropdown-item"  href="#">Something else here</a></li>
                <li><a role="dropdown-item"  href="#"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></a></li>
                                                      <% end %>
          </ul>
        </li>
        </div>
    </ul>
</nav>
<body>
  <% if(@post && @comments) %>
    <%= content_tag :div,
      id: "comments_data",
      content:  post_comments_path(@post),
      current_user: current_user.user_name do %>
    <% end %>
  <% end %>
<% if notice %>
  <p class="notice flex-container"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert flex-container"><%= alert %></p>
<% end %>

  <%= yield %>
</body>
</html>

app/views/likes/_button.html.erb
<% if current_user.liked?(post) %>
  <%=button_to unlike_path(post_id: post.id), remote: true, method: :delete, :class => 'button-like like' do%>
    <span class="fa fa-heart"></span>
  <% end %>
<% else %>
  <%= button_to like_path(post_id: post.id), remote: true, :class => 'button-like' do%>
    <span class="fa fa-heart"></span>
  <% end %>
<% end %>

app/views/likes/like.js.erb
$('div#<%=dom_id(@post)%>').html('<%= j render partial: "button", locals: {post: @post}%>');

app/views/likes/unlike.js.erb
$('div#<%=dom_id(@post)%>').html('<%= j render partial: "button", locals: {post: @post}%>');

app/views/pages/front.html.erb
<h1><%= javascript_pack_tag 'hello_react' %></h1>

app/views/posts/_modal.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
  </div>
  <div class="modal-body">

    <div>
      <%= javascript_pack_tag 'application' %>
        <!-- <div class="container-fluid"> -->
        <div class="container">

          <div class="row">
            <div class="post-image post-options col-md-8 col-md-pull">
              <a><%= @post.user.user_name %></a>
              <div class="post-image">
                <%= image_tag @post.image, :width => "650", :height => "auto", :crop => "scale" %>
                <%= div_for @post do %>
                <%=  render partial: "likes/button", locals: {post: @post} %>
                <% end  %>
              </div>
            </div>
            <div class="col-md-4 col-md-push" id="react">
              <%= content_tag :div,
              id: "comments_data",
              content:  post_comments_path(@post),
              current_user: current_user.user_name do %>
              <% end %>
            </div>
          </div>
        </div>
          <!-- </div> -->
        </div>

        <!-- , props: {content: post_comments_path(@post), data: @post.comments.to_json}) -->

    </div>
      <div class="comment-form">
        <% if @post.user.id == current_user.id %>
        <%= link_to "Edit", edit_post_path(@post) %>
        <% else %>
        <% end %>
        <div>
        <%= link_to "Back to Posts", posts_path %>
        <div>
      </div>

    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary">Save changes</button>
  </div>
</div>
</div>

app/views/posts/edit.html.erb
<%= simple_form_for @post do |f| %>
  <%= image_tag @post.image, width: 600 %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Delete Post", post_path(@post), method: :delete %>
<%= link_to "Cancel", post_path(@post) %>

app/views/posts/index.html.erb
<div class="container">
    <% @posts.in_groups_of(3).each do |group| %>
    <div class="row justify-content-md-center">
      <% group.each do |post| %>
        <%unless post.nil?  %>
      <div class="col-md-4 indeximage" id="grid-container">
          <%=link_to post_path(post), remote: true, class: 'static-popup-link' do %>
                                        <%= image_tag post.image, size: "300x300", :weight => "face", class: "img-grid" %>
                                          <%= content_tag(:span, class: 'text-content') do%>
                                            <%= content_tag(:p, fa_icon("comment", text: "#{post.comments.length}"), class: 'grid-icon grid-icon-comment')%>
                                            <%= content_tag(:p, fa_icon("heart", text: "#{post.likes.length}"), class: 'grid-icon grid-icon-like')%>
                                        <% end %>
                                    <% end %>
        <div class="image-caption">
          <%= post.user.user_name %>
          <%= post.caption %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">Loading...</div>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <div class="posts-form">


  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>


  </div>

<% end %>
<div id="root">

</div>

app/views/posts/show.html.erb
<div>
    <!-- <div class="container-fluid"> -->
      <div class="row">
        <div class="post-image post-options col-md-6 col-md-push">
          <a><%= @post.user.user_name %></a>
          <div class="post-image">
            <%= image_tag @post.image, :width => "650", :height => "auto", :crop => "scale" %>
            <%= div_for @post do %>
            <%=  render partial: "likes/button", locals: {post: @post} %>
            <% end  %>
          </div>
        </div>
        <%= react_component("application")%>
        <div class="col-md-6 col-md-pull" id="react">
          <%= content_tag :div,
          id: "comments_data",
          content:  post_comments_path(@post),
          current_user: current_user.user_name do %>
          <% end %>
        </div>
      <!-- </div> -->
    </div>

    <!-- , props: {content: post_comments_path(@post), data: @post.comments.to_json}) -->

</div>
  <div class="comment-form">
    <% if @post.user.id == current_user.id %>
    <%= link_to "Edit", edit_post_path(@post) %>
    <% else %>
    <% end %>
    <div>
    <%= link_to "Back to Posts", posts_path %>
    <div>
  </div>

</div>

app/views/posts/show.js.erb
$("#myModal").html("<%= j render('/posts/modal') %>");

$('#myModal').modal('show')
// $('#myModal').on('shown.bs.modal', function () {
//   if(document.createEvent){
//     var evt = document.createEvent("MutationEvents");
//     evt.initMutationEvent("DOMContentLoaded", true, true, document, "", "", "", 0);
//     document.dispatchEvent(evt);
// }
// });

app/views/users/show.html.erb
<div class="container">
    <% @posts.in_groups_of(3).each do |group| %>
    <div class="row justify-content-md-center">
      <% group.each do |post| %>
        <%unless post.nil?  %>
      <div class="col-md-4 indeximage" id="grid-container">
          <%=link_to post_path(post), remote: true, class: 'static-popup-link' do %>
                                        <%= image_tag post.image, size: "300x300", :weight => "face", class: "img-grid" %>
                                          <%= content_tag(:span, class: 'text-content') do%>
                                            <%= content_tag(:p, fa_icon("comment", text: "#{post.comments.length}"), class: 'grid-icon grid-icon-comment')%>
                                            <%= content_tag(:p, fa_icon("heart", text: "#{post.likes.length}"), class: 'grid-icon grid-icon-like')%>
                                        <% end %>
                                    <% end %>
        <div class="image-caption">
          <%= post.user.user_name %>
          <%= post.caption %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">Loading...</div>